#
# Bamboo pre-installation
#

- name: Create Bamboo group
  group: name={{ bamboo_group }} gid={{ bamboo_uid }} system=yes
  when: bamboo_user != "{{ lookup('env', 'USER') }}"

- name: Create Bamboo user
  user: name={{ bamboo_user }} uid={{ bamboo_gid }} system=yes group={{ bamboo_group }}
  when: bamboo_user != "{{ lookup('env', 'USER') }}"

- include: mysql.yml
