aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
aws_ec2_region: us-west-1
aws_ec2_image_id: ami-44613824
aws_ec2_key_name: ANSIBLE_DEFAULT_KEY
aws_ec2_security_group: ANSIBLE_DEFAULT_SECURITY_GROUP
aws_ec2_instance_type: t2.small
aws_ec2_ansible_group: aws_ec2_servers
